about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('data/', views.about_data_page, name = 'about_data_page'),
    path('strategies/', views.about_strategies_page, name = 'about_strategies_page'),
    path('how_to_use/', views.how_to_use, name = 'how_to_use')
]

accounts/urls.py
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.sign_up_view, name='sign_up_view'),
    path('login/', views.login_view, name = 'login_view'),
    path('logout/', views.logout_view, name='logout_view')
]

data/urls.py
from django.urls import path, include
from django.shortcuts import redirect
from . import views

app_name = 'data'

urlpatterns = [

    path('data/', views.get_the_data, name = 'get_the_data'),
]

get_data/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('data.urls')),
    path('crypto/', include('crypto.urls')),
    path('correlation/', include('find_correlation.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('user_posts.urls')),
    path('about/', include('about.urls')),
    path('regression/', include('regression.urls')),
    path('portfolio_optimization/', include('port_optimization.urls'))
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

regression/urls.py
from django.urls import path
from . import views

app_name = 'regression'

urlpatterns = [
    path('', views.regression_home, name = 'regression_home'),
    path('simple_regression/', views.simple_regression, name = 'simple_regression')
]

user_posts/urls.py
from . import views
from django.urls import path

app_name = 'user_posts'

urlpatterns = [
    path('', views.home_posts, name = 'home'),
    path('create_post/', views.create_post, name = 'create_post' ),
    path('<int:user_posts_id>', views.post_detail, name = 'post_detail')
]

get_data/templates/get_data/base.html
<!DOCTYPE html>
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="{% static 'QUANTCORE_PIC.ico'%} ">

  <title>Quant-Core</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link href="dashboard.css" rel="stylesheet">
</head>

<!-- NAVBAR -->

<body>
  <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'user_posts:home' %}">QuantCore</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content" id="navbarsExample01">
      <ul class="navbar-nav ml-auto">
        <div class="navbar-nav">


          <li class="nav-item">
            <a class="nav-link" href="{% url 'data:get_the_data' %}">Get Stock Data</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'regression:regression_home' %}">
              Regression Analysis
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'portfolio_optimization:optimize' %}">
              Port Optimization
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'correlation:find_correlation' %}">
              Correlation
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">
              Strategies
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              Predictive Analytics
            </a>
          </li>
        </ul>
        <hr>

        <ul class="navbar-nav ">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_posts:create_post' %}">
              New Post
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about:how_to_use' %}">
              User Guide
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'about:about_data_page' %}">
              About the Data
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about:about_strategies_page' %}">
              About the Strategies
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">
              References
            </a>
          </li>






          </div>


        </div>
      </div>
    </nav>



<!-- SIDEBAR -->







    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light ">


          <div class=" sidebar-collapse">

            <ul class="nav flex-column">

              <li class="nav-item">
                <a class="nav-link active" href="{% url 'user_posts:home' %}">
                  <span data-feather="home"></span>
                  Home <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'data:get_the_data' %}">
                  <span data-feather="trending-up"></span>
                  Get Stock Data
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'regression:regression_home' %}">
                  <span data-feather="activity"></span>
                  Regression Analysis
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'portfolio_optimization:optimize' %}">
                  <span data-feather="folder"></span>
                  Port Optimization
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'correlation:find_correlation' %}">
                  <span data-feather="aperture"></span>
                  Correlation
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  Strategies
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="layers"></span>
                  Predictive Analytics
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>New Post</span>
              <a class="d-flex align-items-center text-muted" href="{% url 'user_posts:create_post' %}">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>

            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about:how_to_use' %}">
                  <span data-feather="file-text"></span>
                  User Guide
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about:about_data_page' %}">
                  <span data-feather="file-text"></span>
                  About the Data
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  About the Strategies
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  References
                </a>
              </li>


              </ul>
            </div>
          </nav>



          <!-- LOGIN BUTTONS -->


          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
              <h1 class="h2">QuantCore</h1>
              <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group mr-2">
                  {% if user.is_authenticated %}
                  <a  href="javascript:{document.getElementById('logout').submit()}"><button class="btn btn-primary">Logout</button></a>

                  <form class="" id="logout" action="{% url 'accounts:logout_view' %}"  method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="" value="">
                  </form>

                  {% else %}

                  <a class="pr-2" href="{% url 'accounts:login_view' %}"><button class="btn  btn-primary">Login</button></a>
                  <a class="" href="{% url 'accounts:sign_up_view' %}"><button class="btn btn-primary">Signup</button></a>
                  {% endif %}


                </div>

              </div>
            </div>




            <!-- Bootstrap core JavaScript
            ================================================== -->
            <!-- Placed at the end of the document so the pages load faster -->
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
            <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
            <!-- Icons -->
            <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
            <script>
            feather.replace()
            </script>

            <!-- Graphs -->

          </body>
          </html>


          {% block content %}
          {% endblock content %}

          <footer class="container ">
            <p>&copy; QuantCore {% now 'Y' %}</p>
          </footer>
        </body>
        </html>

get_data/templates/get_data/cuts.html
<!DOCTYPE html>
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- <link rel="icon" href="{% static 'favicon.ico'%} "> -->

  <title>Quant-Core</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link href="dashboard.css" rel="stylesheet">
</head>

<!-- NAVBAR -->

<body>
  <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'user_posts:home' %}">QuantCore</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content" id="navbarsExample01">
      <ul class="navbar-nav ml-auto">
        <div class="navbar-nav">

          {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'data:get_the_data' %}">Get Stock Data</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'regression:regression_home' %}">
              Regression Analysis
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'portfolio_optimization:optimize' %}">
              Port Optimization
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'correlation:find_correlation' %}">
              Correlation
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">
              Strategies
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              Predictive Analytics
            </a>
          </li>
        </ul>
        <hr>

        <ul class="navbar-nav ">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_posts:create_post' %}">
              New Post
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about:how_to_use' %}">
              User Guide
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'about:about_data_page' %}">
              About the Data
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about:about_strategies_page' %}">
              About the Strategies
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">
              References
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about:how_to_use' %}">
              User Guide
            </a>
          </li>

          <ul class="nav flex-column mb-2">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about:about_data_page' %}">
                About the Data
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about:about_strategies_page' %}">
                About the Strategies
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="#">
                References
              </a>
            </li>
            {% endif %}






          </div>


        </div>
      </div>
    </nav>



<!-- SIDEBAR -->







    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light ">


          <div class=" sidebar-collapse">

            <ul class="nav flex-column">
              {% if user.is_authenticated %}

              <li class="nav-item">
                <a class="nav-link active" href="{% url 'user_posts:home' %}">
                  <span data-feather="home"></span>
                  Home <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'data:get_the_data' %}">
                  <span data-feather="trending-up"></span>
                  Get Stock Data
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'regression:regression_home' %}">
                  <span data-feather="activity"></span>
                  Regression Analysis
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'portfolio_optimization:optimize' %}">
                  <span data-feather="folder"></span>
                  Port Optimization
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'correlation:find_correlation' %}">
                  <span data-feather="aperture"></span>
                  Correlation
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  Strategies
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="layers"></span>
                  Predictive Analytics
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>New Post</span>
              <a class="d-flex align-items-center text-muted" href="{% url 'user_posts:create_post' %}">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>

            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about:how_to_use' %}">
                  <span data-feather="file-text"></span>
                  User Guide
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about:about_data_page' %}">
                  <span data-feather="file-text"></span>
                  About the Data
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  About the Strategies
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  References
                </a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about:how_to_use' %}">
                  <span data-feather="file-text"></span>
                  User Guide
                </a>
              </li>

              <ul class="nav flex-column mb-2">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'about:about_data_page' %}">
                    <span data-feather="file-text"></span>
                    About the Data
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'about:about_strategies_page' %}">
                    <span data-feather="file-text"></span>
                    About the Strategies
                  </a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    References
                  </a>
                </li>
                {% endif %}

              </ul>
            </div>
          </nav>



          <!-- LOGIN BUTTONS -->


          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
              <h1 class="h2">QuantCore</h1>
              <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group mr-2">
                  {% if user.is_authenticated %}
                  <a  href="javascript:{document.getElementById('logout').submit()}"><button class="btn btn-primary">Logout</button></a>

                  <form class="" id="logout" action="{% url 'accounts:logout_view' %}"  method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="" value="">
                  </form>

                  {% else %}

                  <a class="pr-2" href="{% url 'accounts:login_view' %}"><button class="btn  btn-primary">Login</button></a>
                  <a class="" href="{% url 'accounts:sign_up_view' %}"><button class="btn btn-primary">Signup</button></a>
                  {% endif %}


                </div>

              </div>
            </div>




            <!-- Bootstrap core JavaScript
            ================================================== -->
            <!-- Placed at the end of the document so the pages load faster -->
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
            <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
            <!-- Icons -->
            <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
            <script>
            feather.replace()
            </script>

            <!-- Graphs -->

          </body>
          </html>


          {% block content %}
          {% endblock content %}

          <footer class="container ">
            <p>&copy; QuantCore {% now 'Y' %}</p>
          </footer>
        </body>
        </html>