data/urls.py
from django.urls import path, include
from django.shortcuts import redirect
from . import views

app_name = 'data'

urlpatterns = [

    path('data/', views.get_the_data, name = 'get_the_data'),
]

get_data/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('data.urls')),
    path('crypto/', include('crypto.urls')),
    path('correlation/', include('find_correlation.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('user_posts.urls')),
    path('about/', include('about.urls')),
    path('regression/', include('regression.urls')),
    path('portfolio_optimization/', include('port_optimization.urls'))
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

port_optimization/urls.py
from django.urls import path
from . import views

app_name = 'portfolio_optimization'

urlpatterns = [
    path('', views.optimize, name = 'optimize')
]

regression/urls.py
from django.urls import path
from . import views

app_name = 'regression'

urlpatterns = [
    path('', views.regression_home, name = 'regression_home'),
    path('simple_regression/', views.simple_regression, name = 'simple_regression')
]

port_optimization/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models





# class sharpe_ratio_analysis(models.Model):
#
#     portfolio = models.TextField()
#     sharpe = models.TextField()
#     start_date = models.TextField()
#     end_date = models.TextField()
#     user = models.ForeignKey(User, on_delete = models.CASCADE)
#
#     def __str__(self):
#         return self.sharpe

port_optimization/views.py
from django.shortcuts import render
from data import views as data_views
from datetime import datetime
import datetime as dt
import pandas as pd
import numpy as np
from . import tables
from . import plots
from . import models
import pandas as pd
import pandas_datareader as web
from django.contrib.auth.models import User
from iexfinance.stocks import get_historical_data


def optimize(request):
    if request.method == "POST":
        try:
            tickers = request.POST['Tickers']

            tickers = tickers.upper()



            print(tickers)
            print(type(tickers))
            if type(tickers) != list:
                if "'" in tickers:
                    tickers = tickers.replace("'", '')
                tickers = tickers.replace(',  ', ', ')
                tickers = str(tickers)
                tickers = tickers.split(', ')

                tickers = list(tickers)

            amount = request.POST['Amount']
            if ',' in amount:
                amount = amount.replace(',','')

            # start = datetime.strptime(request.POST['start'],'%Y-%m-%d')
            start = pd.to_datetime(request.POST['start'])
            # if len(tickers) > 7:
            #     start = pd.to_datetime('2013-06-01')
            if len(tickers) > 30:
                tickers = tickers[:30]
            if start < (datetime.now() - dt.timedelta(weeks = (52*5))):
                start = datetime.now() - dt.timedelta(weeks = (52*4))
            #start = pd.to_datetime('2015-06-01')
            tickers = tickers


            end = pd.to_datetime(request.POST['end'])
            if end > datetime.now():
                end = datetime.now()
            datatype = 'stock_data'
            # database = pd.DataFrame()
            # """NON OPTIMAL PORTFOLIO"""
            #
            # for ticker, allocation in zip(tickers, [1/len(tickers) for ticker in tickers]):
            #     data = data_views.get_stock_data(datatype, ticker, start, end)
            #     data = data.loc[:, ['AdjAdjClose']]
            #
            #     data.rename(columns = {'AdjAdjClose':ticker}, inplace = True)
            #     data[ticker + ' Normed_Returns'] = data[ticker]/data[ticker].iloc[0]
            #     data[ticker + ' Allocation'] = data[ticker + ' Normed_Returns']*allocation
            #     data[ticker + ' Position_values'] = data[ticker + ' Allocation']*int(amount)
            #     database = database.join(data, how = 'outer')
            #     database.dropna(inplace = True)

            data = pd.DataFrame()

            dataframe = pd.DataFrame()

            for stock in tickers:
                stock_data = get_historical_data(stock,start = start, end = end,token ='sk_6d1c2037a984473895a42a17710cf794', output_format = 'pandas', close_only=True)

                stock_data = stock_data[['close']]
                stock_data.rename(columns = {'close':stock}, inplace = True)
                dataframe = pd.concat([dataframe, stock_data], axis = 1)


            database = pd.DataFrame()
            for ticker, allocation in zip(tickers, [1/len(tickers) for ticker in tickers]):
                data = pd.DataFrame(dataframe[ticker])

                #data = data.loc[:, ['AdjClose']]
                #data.rename(columns = {'AdjClose':ticker}, inplace = True)
                data[ticker + ' Normed_Returns'] = data[ticker]/data[ticker].iloc[0]
                data[ticker + ' Allocation'] = data[ticker + ' Normed_Returns']*allocation
                data[ticker + ' Position_values'] = data[ticker + ' Allocation']*int(amount)
                database = database.join(data, how = 'outer')
                database.dropna(inplace = True)


            non_optimal_position_val = pd.DataFrame()
            for ticker in tickers:
                non_optimal_position_val = pd.concat([non_optimal_position_val, database[ticker + ' Position_values']],axis = 1)

            non_optimal_position_val['Total_position'] = non_optimal_position_val.sum(axis=1)

            """CALCULATE LOG RETURNS"""
            log_df = pd.DataFrame()
            for ticker in tickers:
                log_df = pd.concat([log_df, database[ticker]], axis = 1)

            log_ret = np.log(log_df/log_df.shift(1))



            """OPTIMIZATION"""

            num_ports = 8000
            if len(tickers) > 10:
                num_ports = 3000
            all_weights = np.zeros((num_ports, len(tickers)))
            ret_arr = np.zeros(num_ports)
            vol_arr = np.zeros(num_ports)
            sharpe_arr = np.zeros(num_ports)

            for ind in range(num_ports):
                weights = np.array(np.random.random(len(tickers)))
                weights = weights/np.sum(weights)

                all_weights[ind,:] = weights

                ret_arr[ind] = np.sum((log_ret.mean() * weights) * 252)
                vol_arr[ind]= np.sqrt(np.dot(weights.T, np.dot(log_ret.cov()*252, weights)))

                sharpe_arr[ind] = ret_arr[ind]/vol_arr[ind]
            max_sharpe = sharpe_arr.argmax()
            optimized_weights = all_weights[max_sharpe,:]
            sharpe_ratio = sharpe_arr[max_sharpe].round(3)
            max_ret = ret_arr[max_sharpe]
            max_vol = vol_arr[max_sharpe]
            bullet = plots.market_bullet(vol_arr, ret_arr, sharpe_arr, max_vol, max_ret)
            weights_ticks_df = pd.DataFrame()

            opt_weights_series = pd.Series(optimized_weights, name='Weights')
            tickers_series = pd.Series(tickers, name = 'Tickers')
            weights_ticks_df = pd.concat([weights_ticks_df,tickers_series, opt_weights_series ], axis = 1)





            """OPTIMAL PLOT"""
            datatype = 'stock_data'

            data = pd.DataFrame()

            dataframe = pd.DataFrame()

            for stock in tickers:
                stock_data = get_historical_data(stock,start = start, end = end,token ='sk_6d1c2037a984473895a42a17710cf794', output_format = 'pandas', close_only=True)
                stock_data = stock_data[['close']]
                stock_data.rename(columns = {'close':stock}, inplace = True)
                dataframe = pd.concat([dataframe, stock_data], axis = 1)



            database = pd.DataFrame()
            for ticker, allocation in zip(tickers, optimized_weights):
                data = pd.DataFrame(dataframe[ticker])

                #data = data.loc[:, ['AdjClose']]
                #data.rename(columns = {'AdjClose':ticker}, inplace = True)
                data[ticker + ' Normed_Returns'] = data[ticker]/data[ticker].iloc[0]
                data[ticker + ' Allocation'] = data[ticker + ' Normed_Returns']*allocation
                data[ticker + ' Position_values'] = data[ticker + ' Allocation']*int(amount)
                database = database.join(data, how = 'outer')
                database.dropna(inplace = True)



            # for ticker, allocation in zip(tickers, optimized_weights):
            #     data = data_views.get_stock_data(datatype, ticker, start, end)
            #     data = data.loc[:, ['AdjAdjClose']]
            #     data.rename(columns = {'AdjAdjClose':ticker}, inplace = True)
            #     data[ticker + ' Normed_Returns'] = data[ticker]/data[ticker].iloc[0]
            #     data[ticker + ' Allocation'] = data[ticker + ' Normed_Returns']*allocation
            #     data[ticker + ' Position_values'] = data[ticker + ' Allocation']*int(amount)
            #     database = database.join(data, how = 'outer')
            optimal_position_val = pd.DataFrame()
            for ticker in tickers:
                optimal_position_val = pd.concat([optimal_position_val, database[ticker + ' Position_values']],axis = 1)

            optimal_position_val['Total_position'] = optimal_position_val.sum(axis=1)


            portfolio_plot = plots.optimal_plot(non_optimal_position_val['Total_position'], optimal_position_val['Total_position'], start, end)


            portfolio_table = pd.concat([optimal_position_val['Total_position'].round(2),non_optimal_position_val['Total_position'].round(2)],axis = 1)

            portfolio_table.columns = ['Optimal Position Value','Non Optimal Position Value']
            # global global_portfolio_optimal_non_optimal
            global_portfolio_optimal_non_optimal = portfolio_table.to_json()
            request.session['global_portfolio_optimal_non_optimal'] = global_portfolio_optimal_non_optimal
            # placeholder = optimal_portfolio_global_holder()


            portfolio_table['Difference'] = portfolio_table['Optimal Position Value'] - portfolio_table['Non Optimal Position Value']
            table = tables.make_stock_table(portfolio_table.round(2))

            weights_table = tables.weights(weights_ticks_df.round(2))



            return render(request, 'port_optimization/optimized.html', {'global_portfolio_optimal_non_optimal':global_portfolio_optimal_non_optimal ,'sharpe_ratio':sharpe_ratio, 'weights_table':weights_table,'table':table,'tickers':tickers, 'portfolio_plot':portfolio_plot, 'bullet':bullet})



        except Exception as e:
            print(e)
            print(e.args)
            error_message = e
            error = 'One or more of your inputs was not accepted: '
            return render(request, 'port_optimization/optimization_form.html', {'error':error, 'error_message':error_message})

    return render(request, 'port_optimization/optimization_form.html')

port_optimization/templates/port_optimization/optimization_form.html
<!DOCTYPE html>
{% extends "get_data/base.html" %}

{% block content %}

<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>Getting Data</title>
</head>
<body>
  <div class="container">
    <h1>Portfolio Optimization</h1>
    <h3>Fill in the following fields</h3>
    <h6>Enter your tickers in with a following comma and a space, I.E. AAPL, GE, TSLA</h6>
    <h6>We only have data from the past five years until late March of 2018</h6>
    <h6>Email me for portfolios consisting of more than 30 tickers</h6>

    {{error}}
    {{error_message}}




    <form class="" action="{% url 'portfolio_optimization:optimize' %}" method="post">
      <div class="form-group">


        {% csrf_token %}
        <label for="StartDate">Start Date:</label>
        <input type="date" class="form-control" id="StartDate" name="start" value="">

        <label for="EndDate">End Date:</label>
        <input type="date" class="form-control" id="EndDate" name="end" value="">
        <label for="Amount">Amount of allocation in dollars:</label>
        <input type="text" id="Amount" class="form-control"name="Amount" placeholder="Please enter the amount allocated to this portfolio">
        <label for="Tickers">Tickers:</label>
        <input type="text" id="Tickers" class="form-control"name="Tickers" placeholder="Please add a ticker">




        <br>
        <input type="submit" class="btn btn-primary" value="Get Data">
      </div>
    </div>

  </form>

</body>
</html>
{% endblock content %}

port_optimization/templates/port_optimization/optimized.html
{% extends "get_data/base.html" %}





{% load staticfiles %}

{% block content %}
<div class="container">
  <h1>Your Portfolio Optimized Vs. Non Optimized </h1>
  <hr>
  <h5>Sharpe Ratio: {{sharpe_ratio}}</h5>
  {# <img src="{% static 'data.png' %}" alt=""class="img-fluid" alt="Responsive image"> #}


</div>


<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <div class="container-fluid">
        {{portfolio_plot|safe}}
      </div>

    </div>
    <div class="col-md-4">
      <div class="container-fluid">
        {{bullet|safe}}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">

      <form class="" action="{% url 'regression:simple_regression' %}" method="post">
        <div class="form-group">
          {% csrf_token %}
          <label for="exampleFormControlSelect1">Would you like to run a regression on your portfolio?</label>
          <select class="form-control" id="exampleFormControlSelect1" name='datatype1'>
            <option value="run">Yes</option>
            <option value='do_not_run'>No</option>


          </select>
        </div>
        <input type="submit" class="btn btn-primary" value="Run Regression">


      </form>

    </div>



  </div>
  <br>
  <div class="row">
    <div class="col-md-8">
      <div class="container-fluid">
        {{table|safe}}

      </div>

    </div>
    <div class="col-md-4">
      <div class="container-fluid">
        {{weights_table|safe}}

      </div>

    </div>

  </div>
</div>
{% endblock content %}