about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('data/', views.about_data_page, name = 'about_data_page'),
    path('strategies/', views.about_strategies_page, name = 'about_strategies_page'),
    path('how_to_use/', views.how_to_use, name = 'how_to_use')
]

data/urls.py
from django.urls import path, include
from django.shortcuts import redirect
from . import views

app_name = 'data'

urlpatterns = [

    path('data/', views.get_the_data, name = 'get_the_data'),
]

get_data/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('data.urls')),
    path('crypto/', include('crypto.urls')),
    path('correlation/', include('find_correlation.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('user_posts.urls')),
    path('about/', include('about.urls')),
    path('regression/', include('regression.urls')),
    path('portfolio_optimization/', include('port_optimization.urls'))
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

user_posts/urls.py
from . import views
from django.urls import path

app_name = 'user_posts'

urlpatterns = [
    path('', views.home_posts, name = 'home'),
    path('create_post/', views.create_post, name = 'create_post' ),
    path('<int:user_posts_id>', views.post_detail, name = 'post_detail')
]

user_posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class User_Posts(models.Model):
    title = models.CharField(max_length = 200)
    pub_date = models.DateTimeField()
    body = models.CharField(max_length = 500)


    url = models.URLField(blank = True, null = True)
    image = models.ImageField(upload_to = 'images/')
    poster = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:50] + ' ...'

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')

user_posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import User_Posts
from django.utils import timezone

# Create your views here.
def home_posts(request):
    posts = User_Posts.objects.order_by('-id')
    return render(request, 'user_posts/home.html', {'hello':'HELLO FROM USER_POSTS', 'posts':posts})


@login_required
def create_post(request):
    if request.method == "POST":
        if request.POST['title'] and request.POST['body'] and request.FILES['screen_shot']:
            post = User_Posts()
            post.title = request.POST['title']
            post.body = request.POST['body']
            if request.POST['URL'].startswith('http://') or request.POST['URL'].startswith('https://'):
                post.url = request.POST['URL']
            elif request.POST['URL']:
                post.url = 'http://' + request.POST['URL']

            post.image = request.FILES['screen_shot']
            post.pub_date = timezone.datetime.now()
            post.poster = request.user
            post.save()
            return redirect('/' + str(post.id))

        else:
            return render(request, 'user_posts/create.html', {'error':'All Fields except URL are required'})

    else:
        return render(request, 'user_posts/create.html')








def post_detail(request, user_posts_id):
    post = get_object_or_404(User_Posts, pk = user_posts_id)
    return render(request, 'user_posts/detail_page.html',{'post':post})

user_posts/templates/user_posts/create.html
{% extends "get_data/base.html" %}

{% block content %}




      <!-- Main jumbotron for a primary marketing message or call to action -->


      <main role="main">

        <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron">
          <div class="container">
            <h1 class="display-3">Welcome to Quant-Core</h1>
            <h3> If you are looking to upload a view of your analysis, please take a screenshot and upload that as your file. </h3>
            {{error}}
            <h3>Create a new post.</h3>

            <hr>
            <hr>
            <form class="" action="{% url 'user_posts:create_post' %}" enctype = 'multipart/form-data'  method="post">
              {% csrf_token %}
              <label for="title">Title:</label>
              <input type="text" class="form-control" id="title" name="title" value="">
              <br>
              <label for="body">Body:</label>
              <textarea class="form-control" id="body" name = 'body' rows="3"></textarea>
              <br>
              <label for="URL">URL:</label>
              <input type="text" class="form-control" id="URL" name="URL" value="">
              <br>
              <label for="screen_shot">Screen Shot:</label>
              <input type="file" class="form-control" id="screen_shot" name="screen_shot" value="">
              <br>

              <br>
              <input type="submit" name="" value="Create Post" class="btn btn-primary">
            </form>

          </div>
        </div>















{% endblock content %}

user_posts/templates/user_posts/detail_page.html
{% extends "get_data/base.html" %}


{% block content %}
  <div class="container">
  <h1>{{post.title}}</h1>
  <hr>
  <hr>
  <img src="{{post.image.url}}" class="img-fluid"alt="">
  <hr>
  <div class="row">
    <div class="col-4">
      <h4>Posted By: {{post.poster.username}}</h4>
    </div>

    <div class="col-8 text-right">
      <h4>Posted on: {{ post.pub_date_pretty}}</h4>
    </div>
    </div>
    {% if post.url %}
    <div class="row">


    <div class="col-12 text-right">
      <p><a href="{{post.url}}">{{post.url}}</a> </p>

    </div>
    </div>
    {% endif %}



  <div class="container-fluid">


<div class="row">


    <div class="col-sm">
      <p>{{post.body}}</p>

          </div>
</div>
      </div>



  </div>






  </div>





{% endblock content %}

user_posts/templates/user_posts/home.html
{% extends "get_data/base.html" %}
{% load staticfiles %}
{% block content %}


      <!-- Main jumbotron for a primary marketing message or call to action -->


      <main role="main">

        <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron">
          <div class="container">
            <h1 class="display-3">Welcome to QuantCore</h1>

            {% if user.is_authenticated %}
            <h4>Quantcore Analytics Version 1.0</h4>
            <p>This is a data analytics/statistical analysis platform built for anyone who wants to see data from various different perspectives.
               You will be able to create correlation matrices,plot heat maps, develop trading strategies, and use regressions for market predictions.
               <br>
               <br>
               If you are unfamiliar with or have any questions about the platform, please reference the about pages, starting with the  <a href="{% url 'about:how_to_use' %}">User Guide</a>. If you still want to know more, shoot me an email.
               The website is built in python, and it is aimed at providing an easy to use interface without sacrificing its Quant Core.
            </p>
            <hr>
            <hr>
            <p><a class="btn btn-primary btn-lg" href="mailto:sking8484@gmail.com" role="button">Email &raquo;</a></p>

            {% else %}
            <h4>Quantcore Analytics Version 1.0</h4>
            <p>This is a data analytics/statistical analysis platform built for anyone who wants to see data from various different perspectives.
               You will be able to create correlation matrices,plot heat maps, develop trading strategies, and use regressions for market predictions.
               <br>
               <br>
               If you are unfamiliar with or have any questions about the platform, please reference the about pages, starting with the  <a href="{% url 'about:how_to_use' %}">User Guide</a>. If you still want to know more, shoot me an email.
               The website is built in python, and it is aimed at providing an easy to use interface without sacrificing its Quant Core.
            </p>
            <hr>
            <hr>

            {% endif %}


          </div>
        </div>







        <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
            {% for post in posts.all %}
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <img class="card-img-top" src="{{post.image.url}}" alt="">
                <div class="card-body">
                  <h3 class="card-text">{{post.title}}</h3>
                  <hr>
                  <p class="card-text">{{post.summary}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <a href="{% url 'user_posts:post_detail' post.pk %}"><button type="button" class="btn btn-primary">View</button></a>
                    </div>
                    <small class="text-muted">{{post.pub_date_pretty}}</small>
                  </div>
                </div>
              </div>
            </div>

            {% endfor %}
      </main>










{% endblock content %}