data/urls.py
from django.urls import path, include
from django.shortcuts import redirect
from . import views

app_name = 'data'

urlpatterns = [

    path('data/', views.get_the_data, name = 'get_the_data'),
]

find_correlation/urls.py
from . import views
from django.urls import path

app_name = 'correlation'

urlpatterns = [
    path('', views.find_correlation, name = 'find_correlation')
]

get_data/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('data.urls')),
    path('crypto/', include('crypto.urls')),
    path('correlation/', include('find_correlation.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('user_posts.urls')),
    path('about/', include('about.urls')),
    path('regression/', include('regression.urls')),
    path('portfolio_optimization/', include('port_optimization.urls'))
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

find_correlation/views.py
from django.shortcuts import render
from django.shortcuts import render
import pandas as pd
import pandas_datareader as web
import matplotlib.pyplot as plt
from datetime import datetime
import quandl
from . import plots, tables
import numpy as np
from data import views as data_views




def find_correlation(request):
    if request.method == 'POST':
        datatype_1 = request.POST['datatype1']
        datatype_2 = request.POST['datatype2']
        datatype_3 = request.POST['datatype3']
        datatype_4 = request.POST['datatype4']
        ticker1 = request.POST['symbol1'].upper()
        ticker2 = request.POST['symbol2'].upper()
        ticker3 = request.POST['symbol3'].upper()
        ticker4 = request.POST['symbol4'].upper()

        start = pd.to_datetime(request.POST['start'])
        end = pd.to_datetime(request.POST['end'])
        try:
            if datatype_1 == 'stock_data':
                corr_data_1 = data_views.get_stock_data(datatype_1, ticker1, start, end)
                corr_data_1 = corr_data_1['close']/corr_data_1['close'].iloc[0]
                corr_data_1.rename(ticker1, inplace = True)

            if datatype_1=='real_estate':
                corr_data_1 = data_views.get_stock_data(datatype_1,ticker1,start,end)
                corr_data_1.columns = ([ticker1])
            if datatype_1 =='economic':
                corr_data_1 = data_views.get_stock_data(datatype_1, ticker1, start, end)
                corr_data_1 = corr_data_1.iloc[:, 0]
                corr_data_1.rename(ticker1, inplace = True)

            if datatype_2 == 'stock_data':
                corr_data_2 = data_views.get_stock_data(datatype_2, ticker2, start, end)
                corr_data_2 = corr_data_2['close']/corr_data_2['close'].iloc[0]
                corr_data_2.rename(ticker2, inplace = True)

            if datatype_2 == 'real_estate':
                corr_data_2 = data_views.get_stock_data(datatype_2,ticker2,start,end)
                corr_data_2.columns = ([ticker2])

            if datatype_2 =='economic':
                corr_data_2 = data_views.get_stock_data(datatype_2, ticker2, start, end)
                corr_data_2 = corr_data_2.iloc[:, 0]
                corr_data_2.rename(ticker2, inplace = True)

            if datatype_3 == 'stock_data':

                corr_data_3 = data_views.get_stock_data(datatype_3, ticker3, start, end)
                corr_data_3 = corr_data_3['close']/corr_data_3['close'].iloc[0]
                corr_data_3.rename(ticker3, inplace = True)

            if datatype_3 == 'real_estate':

                corr_data_3 = data_views.get_stock_data(datatype_3,ticker3,start,end)
                corr_data_3.columns = ([ticker3])
            if datatype_3 =='economic':
                corr_data_3 = data_views.get_stock_data(datatype_3, ticker3, start, end)
                corr_data_3 = corr_data_3.iloc[:, 0]
                corr_data_3.rename(ticker3, inplace = True)

            if datatype_4 == 'stock_data':


                corr_data_4 = data_views.get_stock_data(datatype_4, ticker4, start, end)
                corr_data_4 = corr_data_4['close']/corr_data_4['close'].iloc[0]
                corr_data_4.rename(ticker4, inplace = True)

            if datatype_4 == 'real_estate':

                corr_data_4 = data_views.get_stock_data(datatype_4,ticker4,start,end)
                corr_data_4.columns = ([ticker4])
            if datatype_4 =='economic':
                corr_data_4 = data_views.get_stock_data(datatype_4, ticker4, start, end)
                corr_data_4 = corr_data_4.iloc[:, 0]
                corr_data_4.rename(ticker4, inplace = True)




            corr_data_df = pd.DataFrame()
            if datatype_3 != 'none' and datatype_4 != 'none':
                corr_data_df = corr_data_df.join([corr_data_1, corr_data_2, corr_data_3, corr_data_4], how='outer')

            if datatype_3 != 'none' and datatype_4 == 'none':
                corr_data_df = corr_data_df.join([corr_data_1, corr_data_2, corr_data_3], how = 'outer')

            if datatype_3 == 'none' and datatype_4 == 'none':
                corr_data_df = corr_data_df.join([corr_data_1, corr_data_2], how = 'outer')

            corr_data_df.dropna(inplace = True)
            corr_df = corr_data_df.corr()
            corr_df.dropna(inplace = True)

            heatmap = plots.correlation_heatmap(corr_df)
            plot = plots.correlation_plot(corr_data_df)
            table = tables.make_corr_table(corr_data_df)
        except Exception as e:
            error_message = e
            error = 'One or more of your inputs was not accepted: '
            return render(request, 'find_correlation/correlation_template.html', {'error':error, 'error_message':error_message})




        return render(request, 'find_correlation/correlation_charts.html', {
                                                                            'heatmap':heatmap,
                                                                            'plot':plot,
                                                                            'table':table,
                                                                            },
                                                                        )
    return render(request, 'find_correlation/correlation_template.html')

find_correlation/templates/find_correlation/correlation_charts.html
{% extends "get_data/base.html" %}





{% load staticfiles %}

{% block content %}
<div class="container">
  <h1>The correlation is : </h1>
{# <img src="{% static 'data.png' %}" alt=""class="img-fluid" alt="Responsive image"> #}


</div>

{{corr_coef}}
<br>
{{corr_message}}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <div class="container-fluid">
        {{plot|safe}}
      </div>

    </div>
    <div class="col-md-4">
      <div class="container-fluid">
        {{heatmap|safe}}
      </div>


    </div>




</div>

</div>



{{table|safe}}







</div>
{% endblock content %}

find_correlation/templates/find_correlation/correlation_template.html
<!DOCTYPE html>
{% extends "get_data/base.html" %}

{% block content %}

<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>Getting Data</title>
</head>
<body>
  <div class="container">
    <h1>Correlation Matrix</h1>
    <h3>Fill in the following fields</h3>
    <h6>If you would like to grab real estate data, please go <a href="https://www.quandl.com/data/ZILLOW-Zillow-Real-Estate-Research">Here</a> </h6>
    <h6>If you would like to grab macro economic data, please go <a href="https://www.quandl.com/data/YALE-Yale-Department-of-Economics?keyword=">Here</a> </h6>

    {{ error }}
    {{ error_message }}

    <form class="" action="{% url 'correlation:find_correlation' %}" method="post">
      <div class="form-group">


        {% csrf_token %}
        <br>
        <label for="StartDate">Start Date:</label>
        <input type="date" class="form-control" id="StartDate" name="start" value="">

        <label for="EndDate">End Date:</label>
        <input type="date" class="form-control" id="EndDate" name="end" value="">
        <br>

        <label for="data1">First Data input:</label>
        <input type="text" id="data1" class="form-control"name="symbol1" placeholder="Please add a ticker">



        <div class="form-group">
          <label for="exampleFormControlSelect1">Data Type 1:</label>
          <select class="form-control" id="exampleFormControlSelect1" name='datatype1'>
            <option value="stock_data">Stock Data</option>
            <option value='real_estate'>Real Estate</option>
            <option value='economic'>Economic Data</option>


          </select>
        </div>

        <br>
        <label for="data2">Second Data Input:</label>
        <input type="text" id="data2" class="form-control"name="symbol2" placeholder="Please add a ticker">



        <div class="form-group">
          <label for="exampleFormControlSelect1">Data Type 2:</label>
          <select class="form-control" id="exampleFormControlSelect1" name='datatype2'>
            <option value="stock_data">Stock Data</option>
            <option value='real_estate'>Real Estate</option>
            <option value='economic'>Economic Data</option>


          </select>
        </div>
        <br>

        <label for="data2">Third Data Input:</label>
        <input type="text" id="data2" class="form-control"name="symbol3" placeholder="Please add a ticker">

        <div class="form-group">
          <label for="exampleFormControlSelect1">Data Type 3:</label>
          <select class="form-control" id="exampleFormControlSelect1" name='datatype3'>
            <option value="none">None</option>
            <option value="stock_data">Stock Data</option>
            <option value='real_estate'>Real Estate</option>
            <option value='economic'>Economic Data</option>



          </select>
        </div>
        <br>

        <label for="data4">Fourth Data Input:</label>
        <input type="text" id="data4" class="form-control"name="symbol4" placeholder="Please add a ticker">


        <div class="form-group">
          <label for="exampleFormControlSelect1">Data Type 4:</label>
          <select class="form-control" id="exampleFormControlSelect1" name='datatype4'>
            <option value="none">None</option>

            <option value="stock_data">Stock Data</option>
            <option value='real_estate'>Real Estate</option>
            <option value='economic'>Economic Data</option>



          </select>
        </div>
        <br>



        <input type="submit" class="btn btn-primary" value="Get Data">
      </div>
    </div>

  </form>

</body>
</html>
{% endblock content %}